package windows;
 import java.awt.Image;
 import java.awt.Toolkit;
 import ucenfotec.progra2.examen2.*;
 //import java.sql.DriverManager;
/**
 *
 * @author Jazmin Arias
 */
public class Interfaz extends javax.swing.JFrame {
        Login registro = new Login();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null); 
        jLayeredPane1.setVisible(false);
    }
    
    public static Image setIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage("images/mail.png");
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jButton1VerLogin = new javax.swing.JButton();
        jButtonQuerellante = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/02982_800x480.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(51, 51, 255));
        salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.setMaximumSize(new java.awt.Dimension(137, 137));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 30));

        jButton1VerLogin.setBackground(new java.awt.Color(51, 51, 255));
        jButton1VerLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1VerLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButton1VerLogin.setText("Iniciar Sesión");
        jButton1VerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1VerLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1VerLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 30));

        jButtonQuerellante.setBackground(new java.awt.Color(51, 51, 255));
        jButtonQuerellante.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonQuerellante.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuerellante.setText("Buscar");
        jButtonQuerellante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuerellanteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonQuerellante, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled-1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(10, 0, 240, 240);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 110, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/02982_800x480.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void jButtonQuerellanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuerellanteActionPerformed
        
        
    }//GEN-LAST:event_jButtonQuerellanteActionPerformed

    private void jButton1VerLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1VerLoginActionPerformed
        
    }//GEN-LAST:event_jButton1VerLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1VerLogin;
    private javax.swing.JButton jButtonQuerellante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
